### ISSUE TITLE
NavLink logic for FlashCards

### ISSUE THREAD

**Issue by Ewu694** [lausan3/hs-dsa-flashcards#15]
NavLink logic to be implemented:

If User is logged in, take them straight to the flashcards page

If User is not logged in, direct them to the sign-in page if they click on the flashcards tab

**Comment by lausan3** [comment]
closed with https://github.com/lausan3/hs-dsa-flashcards/pull/16/commits/6936998e736449758a4d3df867648a94fb5c66ce
